{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-riskmetric
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/riskmetric_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/riskmetric/riskmetric_{{ version }}.tar.gz
  sha256: 02a2f542a97d4c62481ecd3c4a1c0b684c3864b74ea552974672727f0d61e0a0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-biocmanager
    - r-backports
    - r-covr
    - r-cranlogs
    - r-curl
    - r-devtools
    - r-httr
    - r-memoise
    - r-pillar
    - r-pkgload
    - r-tibble
    - r-urltools
    - r-vctrs
    - r-xml2
  run:
    - r-base
    - r-biocmanager
    - r-backports
    - r-covr
    - r-cranlogs
    - r-curl
    - r-devtools
    - r-httr
    - r-memoise
    - r-pillar
    - r-pkgload
    - r-tibble
    - r-urltools
    - r-vctrs
    - r-xml2

test:
  commands:
    - $R -e "library('riskmetric')"           # [not win]
    - "\"%R%\" -e \"library('riskmetric')\""  # [win]

about:
  home: https://pharmar.github.io/riskmetric/, https://github.com/pharmaR/riskmetric
  license: MIT
  summary: Facilities for assessing R packages against a number of metrics to help quantify their robustness.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
